/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UI_SellKeyWnd from "./UI_SellKeyWnd";
import UI_ExperienceWnd2 from "./UI_ExperienceWnd2";
import UI_Sword_01 from "./UI_Sword_01";
import UI_Sword_02 from "./UI_Sword_02";
import UI_Sword_03 from "./UI_Sword_03";
import UI_Shield_01 from "./UI_Shield_01";
import UI_Shield_02 from "./UI_Shield_02";
import UI_Shield_03 from "./UI_Shield_03";
import UI_Nugget from "./UI_Nugget";
import UI_KeyBox from "./UI_KeyBox";
import UI_Feather_01 from "./UI_Feather_01";
import UI_Feather_02 from "./UI_Feather_02";
import UI_Badge from "./UI_Badge";
import UI_Wheel from "./UI_Wheel";
import UI_Cross from "./UI_Cross";
import UI_LifeBottle from "./UI_LifeBottle";
import UI_Hammer from "./UI_Hammer";
import UI_MapItem from "./UI_MapItem";
import UI_ExplainScreen from "./UI_ExplainScreen";
import UI_door_yellow from "./UI_door_yellow";
import UI_door_blue from "./UI_door_blue";
import UI_door_red from "./UI_door_red";
import UI_door_steel_blue from "./UI_door_steel_blue";
import UI_door_steel_yellow from "./UI_door_steel_yellow";
import UI_door_steel_red from "./UI_door_steel_red";
import UI_door_steel_green from "./UI_door_steel_green";
import UI_wall_steel from "./UI_wall_steel";
import UI_master from "./UI_master";
import UI_trader from "./UI_trader";
import UI_thief from "./UI_thief";
import UI_princess from "./UI_princess";
import UI_Monster01 from "./UI_Monster01";
import UI_Monster02 from "./UI_Monster02";
import UI_Monster03 from "./UI_Monster03";
import UI_Monster04 from "./UI_Monster04";
import UI_Monster05 from "./UI_Monster05";
import UI_Monster06 from "./UI_Monster06";
import UI_Monster07 from "./UI_Monster07";
import UI_Monster08 from "./UI_Monster08";
import UI_Monster09 from "./UI_Monster09";
import UI_Monster10 from "./UI_Monster10";
import UI_Monster11 from "./UI_Monster11";
import UI_Monster12 from "./UI_Monster12";
import UI_Monster13 from "./UI_Monster13";
import UI_Monster14 from "./UI_Monster14";
import UI_Monster15 from "./UI_Monster15";
import UI_Monster16 from "./UI_Monster16";
import UI_Monster17 from "./UI_Monster17";
import UI_Monster18 from "./UI_Monster18";
import UI_Monster19 from "./UI_Monster19";
import UI_Monster20 from "./UI_Monster20";
import UI_Monster21 from "./UI_Monster21";
import UI_Monster25 from "./UI_Monster25";
import UI_Monster26 from "./UI_Monster26";
import UI_Monster27 from "./UI_Monster27";
import UI_Monster28 from "./UI_Monster28";
import UI_Monster30 from "./UI_Monster30";
import UI_Monster32 from "./UI_Monster32";
import UI_Monster33 from "./UI_Monster33";
import UI_Monster34 from "./UI_Monster34";
import UI_Monster35 from "./UI_Monster35";
import UI_ChangeLayerWnd from "./UI_ChangeLayerWnd";
import UI_LayerBtn from "./UI_LayerBtn";
import UI_AttributeWnd from "./UI_AttributeWnd";
import UI_AttributeBar from "./UI_AttributeBar";
import UI_BadgeBar from "./UI_BadgeBar";
import UI_WheelBar from "./UI_WheelBar";
import UI_Blood_red from "./UI_Blood_red";
import UI_Blood_blue from "./UI_Blood_blue";
import UI_Stone_Attack from "./UI_Stone_Attack";
import UI_Stone_Defense from "./UI_Stone_Defense";
import UI_AttributeComp from "./UI_AttributeComp";
import UI_PanelComp from "./UI_PanelComp";
import UI_TxtBtnComp from "./UI_TxtBtnComp";
import UI_LayerComp from "./UI_LayerComp";
import UI_KeyPanelComp from "./UI_KeyPanelComp";
import UI_KnapsackComp from "./UI_KnapsackComp";
import UI_character from "./UI_character";
import UI_GameScreen from "./UI_GameScreen";
import UI_fairy from "./UI_fairy";
import UI_BuyKeyWnd from "./UI_BuyKeyWnd";
import UI_MsgBox from "./UI_MsgBox";
import UI_TransitionWnd from "./UI_TransitionWnd";
import UI_ShopWnd2 from "./UI_ShopWnd2";
import UI_ExperienceWnd from "./UI_ExperienceWnd";
import UI_LifeComp from "./UI_LifeComp";
import UI_shop1 from "./UI_shop1";
import UI_shop2 from "./UI_shop2";
import UI_shop3 from "./UI_shop3";
import UI_HomeScreen from "./UI_HomeScreen";
import UI_ShopWnd from "./UI_ShopWnd";
import UI_Key_yellow from "./UI_Key_yellow";
import UI_Key_blue from "./UI_Key_blue";
import UI_Key_red from "./UI_Key_red";
import UI_UpStairs from "./UI_UpStairs";
import UI_DownStairs from "./UI_DownStairs";
import UI_OperationComp from "./UI_OperationComp";
import UI_Monster22 from "./UI_Monster22";
import UI_FightWnd from "./UI_FightWnd";

export default class MainBinder {
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(UI_SellKeyWnd.URL, UI_SellKeyWnd);
		fgui.UIObjectFactory.setExtension(UI_ExperienceWnd2.URL, UI_ExperienceWnd2);
		fgui.UIObjectFactory.setExtension(UI_Sword_01.URL, UI_Sword_01);
		fgui.UIObjectFactory.setExtension(UI_Sword_02.URL, UI_Sword_02);
		fgui.UIObjectFactory.setExtension(UI_Sword_03.URL, UI_Sword_03);
		fgui.UIObjectFactory.setExtension(UI_Shield_01.URL, UI_Shield_01);
		fgui.UIObjectFactory.setExtension(UI_Shield_02.URL, UI_Shield_02);
		fgui.UIObjectFactory.setExtension(UI_Shield_03.URL, UI_Shield_03);
		fgui.UIObjectFactory.setExtension(UI_Nugget.URL, UI_Nugget);
		fgui.UIObjectFactory.setExtension(UI_KeyBox.URL, UI_KeyBox);
		fgui.UIObjectFactory.setExtension(UI_Feather_01.URL, UI_Feather_01);
		fgui.UIObjectFactory.setExtension(UI_Feather_02.URL, UI_Feather_02);
		fgui.UIObjectFactory.setExtension(UI_Badge.URL, UI_Badge);
		fgui.UIObjectFactory.setExtension(UI_Wheel.URL, UI_Wheel);
		fgui.UIObjectFactory.setExtension(UI_Cross.URL, UI_Cross);
		fgui.UIObjectFactory.setExtension(UI_LifeBottle.URL, UI_LifeBottle);
		fgui.UIObjectFactory.setExtension(UI_Hammer.URL, UI_Hammer);
		fgui.UIObjectFactory.setExtension(UI_MapItem.URL, UI_MapItem);
		fgui.UIObjectFactory.setExtension(UI_ExplainScreen.URL, UI_ExplainScreen);
		fgui.UIObjectFactory.setExtension(UI_door_yellow.URL, UI_door_yellow);
		fgui.UIObjectFactory.setExtension(UI_door_blue.URL, UI_door_blue);
		fgui.UIObjectFactory.setExtension(UI_door_red.URL, UI_door_red);
		fgui.UIObjectFactory.setExtension(UI_door_steel_blue.URL, UI_door_steel_blue);
		fgui.UIObjectFactory.setExtension(UI_door_steel_yellow.URL, UI_door_steel_yellow);
		fgui.UIObjectFactory.setExtension(UI_door_steel_red.URL, UI_door_steel_red);
		fgui.UIObjectFactory.setExtension(UI_door_steel_green.URL, UI_door_steel_green);
		fgui.UIObjectFactory.setExtension(UI_wall_steel.URL, UI_wall_steel);
		fgui.UIObjectFactory.setExtension(UI_master.URL, UI_master);
		fgui.UIObjectFactory.setExtension(UI_trader.URL, UI_trader);
		fgui.UIObjectFactory.setExtension(UI_thief.URL, UI_thief);
		fgui.UIObjectFactory.setExtension(UI_princess.URL, UI_princess);
		fgui.UIObjectFactory.setExtension(UI_Monster01.URL, UI_Monster01);
		fgui.UIObjectFactory.setExtension(UI_Monster02.URL, UI_Monster02);
		fgui.UIObjectFactory.setExtension(UI_Monster03.URL, UI_Monster03);
		fgui.UIObjectFactory.setExtension(UI_Monster04.URL, UI_Monster04);
		fgui.UIObjectFactory.setExtension(UI_Monster05.URL, UI_Monster05);
		fgui.UIObjectFactory.setExtension(UI_Monster06.URL, UI_Monster06);
		fgui.UIObjectFactory.setExtension(UI_Monster07.URL, UI_Monster07);
		fgui.UIObjectFactory.setExtension(UI_Monster08.URL, UI_Monster08);
		fgui.UIObjectFactory.setExtension(UI_Monster09.URL, UI_Monster09);
		fgui.UIObjectFactory.setExtension(UI_Monster10.URL, UI_Monster10);
		fgui.UIObjectFactory.setExtension(UI_Monster11.URL, UI_Monster11);
		fgui.UIObjectFactory.setExtension(UI_Monster12.URL, UI_Monster12);
		fgui.UIObjectFactory.setExtension(UI_Monster13.URL, UI_Monster13);
		fgui.UIObjectFactory.setExtension(UI_Monster14.URL, UI_Monster14);
		fgui.UIObjectFactory.setExtension(UI_Monster15.URL, UI_Monster15);
		fgui.UIObjectFactory.setExtension(UI_Monster16.URL, UI_Monster16);
		fgui.UIObjectFactory.setExtension(UI_Monster17.URL, UI_Monster17);
		fgui.UIObjectFactory.setExtension(UI_Monster18.URL, UI_Monster18);
		fgui.UIObjectFactory.setExtension(UI_Monster19.URL, UI_Monster19);
		fgui.UIObjectFactory.setExtension(UI_Monster20.URL, UI_Monster20);
		fgui.UIObjectFactory.setExtension(UI_Monster21.URL, UI_Monster21);
		fgui.UIObjectFactory.setExtension(UI_Monster25.URL, UI_Monster25);
		fgui.UIObjectFactory.setExtension(UI_Monster26.URL, UI_Monster26);
		fgui.UIObjectFactory.setExtension(UI_Monster27.URL, UI_Monster27);
		fgui.UIObjectFactory.setExtension(UI_Monster28.URL, UI_Monster28);
		fgui.UIObjectFactory.setExtension(UI_Monster30.URL, UI_Monster30);
		fgui.UIObjectFactory.setExtension(UI_Monster32.URL, UI_Monster32);
		fgui.UIObjectFactory.setExtension(UI_Monster33.URL, UI_Monster33);
		fgui.UIObjectFactory.setExtension(UI_Monster34.URL, UI_Monster34);
		fgui.UIObjectFactory.setExtension(UI_Monster35.URL, UI_Monster35);
		fgui.UIObjectFactory.setExtension(UI_ChangeLayerWnd.URL, UI_ChangeLayerWnd);
		fgui.UIObjectFactory.setExtension(UI_LayerBtn.URL, UI_LayerBtn);
		fgui.UIObjectFactory.setExtension(UI_AttributeWnd.URL, UI_AttributeWnd);
		fgui.UIObjectFactory.setExtension(UI_AttributeBar.URL, UI_AttributeBar);
		fgui.UIObjectFactory.setExtension(UI_BadgeBar.URL, UI_BadgeBar);
		fgui.UIObjectFactory.setExtension(UI_WheelBar.URL, UI_WheelBar);
		fgui.UIObjectFactory.setExtension(UI_Blood_red.URL, UI_Blood_red);
		fgui.UIObjectFactory.setExtension(UI_Blood_blue.URL, UI_Blood_blue);
		fgui.UIObjectFactory.setExtension(UI_Stone_Attack.URL, UI_Stone_Attack);
		fgui.UIObjectFactory.setExtension(UI_Stone_Defense.URL, UI_Stone_Defense);
		fgui.UIObjectFactory.setExtension(UI_AttributeComp.URL, UI_AttributeComp);
		fgui.UIObjectFactory.setExtension(UI_PanelComp.URL, UI_PanelComp);
		fgui.UIObjectFactory.setExtension(UI_TxtBtnComp.URL, UI_TxtBtnComp);
		fgui.UIObjectFactory.setExtension(UI_LayerComp.URL, UI_LayerComp);
		fgui.UIObjectFactory.setExtension(UI_KeyPanelComp.URL, UI_KeyPanelComp);
		fgui.UIObjectFactory.setExtension(UI_KnapsackComp.URL, UI_KnapsackComp);
		fgui.UIObjectFactory.setExtension(UI_character.URL, UI_character);
		fgui.UIObjectFactory.setExtension(UI_GameScreen.URL, UI_GameScreen);
		fgui.UIObjectFactory.setExtension(UI_fairy.URL, UI_fairy);
		fgui.UIObjectFactory.setExtension(UI_BuyKeyWnd.URL, UI_BuyKeyWnd);
		fgui.UIObjectFactory.setExtension(UI_MsgBox.URL, UI_MsgBox);
		fgui.UIObjectFactory.setExtension(UI_TransitionWnd.URL, UI_TransitionWnd);
		fgui.UIObjectFactory.setExtension(UI_ShopWnd2.URL, UI_ShopWnd2);
		fgui.UIObjectFactory.setExtension(UI_ExperienceWnd.URL, UI_ExperienceWnd);
		fgui.UIObjectFactory.setExtension(UI_LifeComp.URL, UI_LifeComp);
		fgui.UIObjectFactory.setExtension(UI_shop1.URL, UI_shop1);
		fgui.UIObjectFactory.setExtension(UI_shop2.URL, UI_shop2);
		fgui.UIObjectFactory.setExtension(UI_shop3.URL, UI_shop3);
		fgui.UIObjectFactory.setExtension(UI_HomeScreen.URL, UI_HomeScreen);
		fgui.UIObjectFactory.setExtension(UI_ShopWnd.URL, UI_ShopWnd);
		fgui.UIObjectFactory.setExtension(UI_Key_yellow.URL, UI_Key_yellow);
		fgui.UIObjectFactory.setExtension(UI_Key_blue.URL, UI_Key_blue);
		fgui.UIObjectFactory.setExtension(UI_Key_red.URL, UI_Key_red);
		fgui.UIObjectFactory.setExtension(UI_UpStairs.URL, UI_UpStairs);
		fgui.UIObjectFactory.setExtension(UI_DownStairs.URL, UI_DownStairs);
		fgui.UIObjectFactory.setExtension(UI_OperationComp.URL, UI_OperationComp);
		fgui.UIObjectFactory.setExtension(UI_Monster22.URL, UI_Monster22);
		fgui.UIObjectFactory.setExtension(UI_FightWnd.URL, UI_FightWnd);
	}
}